# Generated by Django 3.2.8 on 2021-11-03 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=32, null=True)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('retired_date', models.DateField()),
                ('used_for_website', models.CharField(max_length=70)),
                ('explanation', models.TextField(max_length=200)),
            ],
        ),
    ]
