# Generated by Django 3.2.8 on 2021-11-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordmodel',
            old_name='explanation',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='passwordmodel',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
