# Generated by Django 3.2.8 on 2021-11-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20211103_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmodel',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='passwordmodel',
            name='description',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='passwordmodel',
            name='used_for_website',
            field=models.CharField(max_length=63),
        ),
    ]
